LOGISTICS_HUB_TICK_FREQUENCY = 20 -- 20 ticks = 0.33s
LOGISTICS_DRILL_TICK_FREQUENCY = 300 -- 300 ticks = 5s
LOGISTICS_DRILL_BATTERY_CHARGED = 110 -- power in MJ

MAX_CONSTRUCTION_REQUESTS = 25 -- per mining hub
